FROM maven:latest AS build
RUN mkdir -p /workspace
WORKDIR /workspace
COPY pom.xml /workspace
COPY src /workspace/src
RUN mvn -Dmaven.test.skip=true -f pom.xml clean package

# STAGE 2: Run
FROM openjdk:17
COPY --from=build /workspace/target/tasty-0.0.1-SNAPSHOT.jar app.jar
COPY src/main/resources/application.properties /app/config/
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]